name: homebrew

on: [push]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - name: Install docker
      run: |
        brew update
        brew install docker

    - name: Install out-of-tree
      # FIXME: Installation from a GitHub commit URL is not supported anymore
      # run: brew install https://raw.githubusercontent.com/out-of-tree/homebrew-repo/${GITHUB_SHA}/out-of-tree.rb
      run: brew install out-of-tree
